### ISSUE TITLE
Cannot get working periapi

### ISSUE THREAD

**Issue by YoelPLG** [baliscope/periapi#5]
Hello!
I have web development knowledges but not so much about python. I'm trying to get working periapi under debian, but it crashes. I tried it under Windows too, but I get identical results:

`Traceback (most recent call last):
  File "C:/Users/Yoel/Desktop/periapi/periapi/__main__.py", line 14, in <module>
    from requests import exceptions
  File "C:\Users\Yoel\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\Users\Yoel\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\packages\__init__.py", line 27, in <module>
    from . import urllib3
  File "C:\Users\Yoel\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "C:\Users\Yoel\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 3, in <module>
    import logging
  File "C:\Users\Yoel\Desktop\periapi\periapi\logging.py", line 11, in <module>
    logging = _logging.getLogger("periapi")
AttributeError: module 'logging' has no attribute 'getLogger'`

I tried to rename logging.py to, for example, customlogging.py and modify the import line, but then crashes here:

`Traceback (most recent call last):
  File "C:/Users/Yoel/Desktop/periapi/periapi/__main__.py", line 17, in <module>
    from . import PeriAPI
ImportError: cannot import name 'PeriAPI'`

What am I doing wrong?

Thanks!

**Comment by baliscope** [comment]
That depends. It looks like you're cloning the repo and trying to run from there. That's fine if you want to develop, but if you're only interested in using the end functionality I strongly suggest installing with pip3 using the following command: `pip3 install https://github.com/baliscope/periapi/archive/master.zip`. That _should_ be platform independent but I haven't tested on Debian.

If you insist on running it manually, do the following:
1. Undo the changes you made to the custom logging file and the associated imports
2. Copy `__main__.py` one level up and rename to something like `run_periapi.py` (whatever strikes your fancy, really)
3. Edit the following imports in `run_periapi.py`:
   
   `from . import PeriAPI` -> `from periapi import PeriAPI`
   `from . import AutoCap` -> `from periapi import AutoCap`
4. You should now have a directory with `run_periapi.py` and the `periapi` folder in it. `cd` to this directory and run `run_periapi.py` with Python 3.

Let me know how this goes for you.

**Comment by YoelPLG** [comment]
Hello again! Thank you for your fast answer!

I have just installed periapi using pip:

yoel@vps191455:/etc/apt/sources.list.d$ sudo pip install
https://github.com/baliscope/periapi/archive/master.zip
Collecting https://github.com/baliscope/periapi/archive/master.zip
  Downloading https://github.com/baliscope/periapi/archive/master.zip
(22.9MB)
    100% |████████████████████████████████| 22.9MB 26kB/s
  Requirement already satisfied (use --upgrade to upgrade): periapi==0.7.8
from https://github.com/baliscope/periapi/archive/master.zip in
/usr/local/lib/python3.4/dist-packages
Requirement already satisfied (use --upgrade to upgrade): oauth2>=1.9 in
/usr/local/lib/python3.4/dist-packages (from periapi==0.7.8)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.10 in
/usr/local/lib/python3.4/dist-packages (from periapi==0.7.8)
Requirement already satisfied (use --upgrade to upgrade): path.py>=8.2 in
/usr/local/lib/python3.4/dist-packages (from periapi==0.7.8)
Requirement already satisfied (use --upgrade to upgrade): httplib2 in
/usr/local/lib/python3.4/dist-packages (from oauth2>=1.9->periapi==0.7.8)

But when I execute periapi, this occurs:

yoel@vps191455:/etc/apt/sources.list.d$ periapi
Traceback (most recent call last):
  File "/usr/local/bin/periapi", line 9, in <module>
    load_entry_point('periapi==0.7.8', 'console_scripts', 'periapi')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in
load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in
load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['**name**'])
  File "/usr/local/lib/python3.4/dist-packages/periapi/**init**.py", line
8, in <module>
    from .autocap import AutoCap
  File "/usr/local/lib/python3.4/dist-packages/periapi/autocap.py", line
10, in <module>
    from periapi.listener import Listener
  File "/usr/local/lib/python3.4/dist-packages/periapi/listener.py", line
6, in <module>
    from periapi.broadcast import Broadcast
  File "/usr/local/lib/python3.4/dist-packages/periapi/broadcast.py", line
7, in <module>
    from dateutil.parser import parse as dt_parse
ImportError: No module named 'dateutil'

Can you help me about this?

Thanks in advance!

2016-09-07 23:49 GMT+02:00 baliscope notifications@github.com:

**Comment by baliscope** [comment]
Do `pip3 install python-dateutil`. That's odd though, I could have sworn it was in requirements.txt which would have made it install already.

**Comment by YoelPLG** [comment]
Thanks again.

Sorry for needing so much help. I hate when people does the same with me!

I already tried to install dateutil, but:

yoel@vps191455:/etc/apt/sources.list.d$ pip install dateutil
Collecting dateutil
  Could not find a version that satisfies the requirement dateutil (from
versions: )
No matching distribution found for dateutil
yoel@vps191455:/etc/apt/sources.list.d$

I don't know how pip works and how can I add a 'repo' or something like
that.

Thanks!

**Comment by baliscope** [comment]
I edited my comment above after you read it - the correct command is `pip3 install python-dateutil`

**Comment by YoelPLG** [comment]
Oh wow. It were python-dateutil!
I was answering via email hahaha. Now it's working!!

Thank you man.

**Comment by baliscope** [comment]
Glad to help. Note that in the future you can use `pip3 install https://github.com/baliscope/periapi/archive/master.zip --upgrade` to update to the latest version.

Fixed: added python-dateutil to requirements.txt.
